apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: learning-app-production

namespace: learning-app

resources:
  - ../../base

namePrefix: prod-

commonLabels:
  environment: production
  tier: production

images:
  - name: learning-app
    newTag: main-latest

replicas:
  - name: learning-app
    count: 5

configMapGenerator:
  - name: app-config
    behavior: merge
    literals:
      - NODE_ENV=production
      - LOG_LEVEL=info
      - METRICS_ENABLED=true
      - CACHE_ENABLED=true

secretGenerator:
  - name: app-secrets
    behavior: merge
    literals:
      - DATABASE_URL=postgresql://user:pass@prod-db:5432/learning_app

patchesStrategicMerge:
  - deployment-patch.yaml
  - ingress-patch.yaml
  - hpa-patch.yaml
  - service-patch.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: learning-app
    path: security-patch.yaml