- op: add
  path: /spec/template/spec/securityContext
  value:
    runAsNonRoot: true
    runAsUser: 1001
    runAsGroup: 1001
    fsGroup: 1001
    seccompProfile:
      type: RuntimeDefault
- op: add
  path: /spec/template/spec/containers/0/securityContext
  value:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1001
    runAsGroup: 1001
    capabilities:
      drop:
        - ALL
    seccompProfile:
      type: RuntimeDefault
- op: add
  path: /spec/template/spec/containers/0/volumeMounts
  value:
    - name: tmp-volume
      mountPath: /tmp
- op: add
  path: /spec/template/spec/volumes
  value:
    - name: tmp-volume
      emptyDir: {}