apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: learning-app-base

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml

commonLabels:
  app: learning-app
  version: v1.0.0

images:
  - name: learning-app
    newTag: latest

configMapGenerator:
  - name: app-config
    literals:
      - NODE_ENV=production
      - PORT=3000

secretGenerator:
  - name: app-secrets
    literals:
      - DATABASE_URL=placeholder

generatorOptions:
  disableNameSuffixHash: true