apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: learning-app-staging

namespace: learning-app-staging

resources:
  - ../../base

namePrefix: staging-

commonLabels:
  environment: staging
  tier: non-production

images:
  - name: learning-app
    newTag: develop-latest

replicas:
  - name: learning-app
    count: 2

configMapGenerator:
  - name: app-config
    behavior: merge
    literals:
      - NODE_ENV=staging
      - LOG_LEVEL=debug
      - METRICS_ENABLED=true

secretGenerator:
  - name: app-secrets
    behavior: merge
    literals:
      - DATABASE_URL=postgresql://user:pass@staging-db:5432/learning_app

patchesStrategicMerge:
  - deployment-patch.yaml
  - ingress-patch.yaml
  - hpa-patch.yaml